import type { Metadata } from "next";
import HomeIcon from '@/icons/home.tsx'
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-sky-50`}>
        <nav className="flex flex-col bg-white px-4 py-2 rounded self-center">
          <a>

          <HomeIcon />
          </a>
          <a>
            Search
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
